---

- name: Create Mesos DNS directory
  file:
    path: /usr/local/mesos-dns
    state: directory

- name: Download Mesos DNS
  get_url:
    url: "https://github.com/mesosphere/mesos-dns/releases/download/{{ mesos_dns_version }}/mesos-dns-{{ mesos_dns_version }}-linux-amd64"
    dest: /usr/local/mesos-dns

- name: Rename Mesos DNS Binary
  command: "mv /usr/local/mesos-dns/mesos-dns-{{ mesos_dns_version }}-linux-amd64 /usr/local/mesos-dns/mesos-dns"

- name: Make Mesos DNS executable
  file:
    path: /usr/local/mesos-dns/mesos-dns
    mode: "u+x,g+x,o+x"

- name: Create Mesos DNS Configuration file
  template:
    src: conf-mesos-dns.j2
    dest: /usr/local/mesos-dns/config.json