---

- name: Add mesos apt-key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: E56151BF

- name: Add mesosphere repository
  apt_repository:
    repo: 'deb http://repos.mesosphere.com/{{ ansible_distribution|lower }} {{ ansible_lsb.codename }} main'
    state: present

- name: Install latest mesos
  apt:
    name: mesos
    state: latest
    update_cache: yes
    cache_valid_time: 3600
