---

- name: Stopping Mesos Master
  service:
    name: mesos-master
    state: stopped

- name: Set Manual Mesos Master Override
  template:
    src: conf-manual-override.j2
    dest: /etc/init/mesos-master.override

- name: Remove Mesos Master from update-rc.d
  command: update-rc.d -f mesos-master remove