---
galaxy_info:
  author: Shpeed
  description: Installs Mesos Slave
  license: Apache
  min_ansible_version: 1.7
  platforms:
    - name: Ubuntu
      versions:
        - trusty
  categories:
    - system
dependencies:
  - { role: mesos-common}