---

- name: Restarting Zookeeper
  service:
    name: zookeeper
    state: restarted

- name: Check Zookeeper Quorum
  wait_for:
    host: "{{ item[0] }}"
    port: "{{ item[1] }}"
    state: started
    timeout: 60
  with_nested:
    - "{{ groups['masters'] }}"
    - [ "{{ zookeeper_client_port }}", "{{ zookeeper_election_port }}"]